create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name \
 vc707_sys_clock_mmcm2 -dir $ipdir -force
set_property -dict [list \
 CONFIG.CLK_IN1_BOARD_INTERFACE {Custom} \
 CONFIG.PRIM_SOURCE {No_buffer} \
 CONFIG.NUM_OUT_CLKS {7} \
 CONFIG.PRIM_IN_FREQ {200.0} \
 CONFIG.CLKIN1_JITTER_PS {50.0} \
 CONFIG.CLKOUT1_USED {true} \
 CONFIG.CLKOUT2_USED {true} \
 CONFIG.CLKOUT3_USED {true} \
 CONFIG.CLKOUT4_USED {true} \
 CONFIG.CLKOUT5_USED {true} \
 CONFIG.CLKOUT6_USED {true} \
 CONFIG.CLKOUT7_USED {true} \
 CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {12.5} \
 CONFIG.CLKOUT1_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT1_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {25.0} \
 CONFIG.CLKOUT2_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT2_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {37.5} \
 CONFIG.CLKOUT3_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT3_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT4_REQUESTED_OUT_FREQ {50.0} \
 CONFIG.CLKOUT4_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT4_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT5_REQUESTED_OUT_FREQ {100.0} \
 CONFIG.CLKOUT5_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT5_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT6_REQUESTED_OUT_FREQ {150.0} \
 CONFIG.CLKOUT6_REQUESTED_PHASE {0.0} \
 CONFIG.CLKOUT6_REQUESTED_DUTY_CYCLE {50.0} \
 CONFIG.CLKOUT7_REQUESTED_OUT_FREQ {100.0} \
 CONFIG.CLKOUT7_REQUESTED_PHASE {180.0} \
 CONFIG.CLKOUT7_REQUESTED_DUTY_CYCLE {50.0} \
] [get_ips vc707_sys_clock_mmcm2]
